name: 'Test gh'
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
    - run: |
        # test gh
        gh pr list --repo https://github.com/jason-parry/runbooks --state merged --json url --jq .[].url --search 'd6322aead012dcbdb1ab670b6dc10cf236f89a0e'